### ISSUE TITLE
Dropdown multiselect menu with an option repeated

### ISSUE THREAD

**Issue by asbag** [DashboardCode/BsMultiSelect#17]
Hi,

I'm running into troubles. I have four selects, everything works ok, but there's a problem with this scenario. If I click on the second select, called "Format", and I select the "Download" option, the first select - called Type - is filled with Download - see first image attached - instead of being filled the second select.  The first select - called Type - has a Download option too - see second image attached - . It only happens when select this option - "Download" . It only happens with the "Download" options which occurs on both selects, it's an option in both selects, If I select another option different from Download everything works properly, but they are only in one select. 

<img width="859" alt="first" src="https://user-images.githubusercontent.com/7681376/67435170-dddeda00-f5eb-11e9-915f-608f02029d7d.png">

<img width="855" alt="second" src="https://user-images.githubusercontent.com/7681376/67435198-e9320580-f5eb-11e9-9de1-1ba1ce7ad9b5.png">

I have an event :
	jQuery("select").change( function () {
		console.log('this is the select '+ $(this).attr('data-value'));
	});
The first select has a "data-value" called gcs-type, the second select has a "data-value" called gcs-format. When I click on "Download" option, the first select seems to be triggered instead of second one, and in the inspector says "this is the select gcs_type
", but If i click on the "On-demand" option everything works ok, and the inspector says "this is the select gcs_format" as expected. 

<img width="884" alt="third" src="https://user-images.githubusercontent.com/7681376/67436823-a540ff80-f5ef-11e9-8d36-681436b902fa.png">

As a result, it only happens to me when a option name is repeated in more than one select. If the option happens in a single select it works as expected.

Is there anything am I doing wrong?

Thank you!!
David

**Comment by rpokrovskij** [comment]
Wow. Your theme is perferct :)

As I understand the problem is that when you click in one dropdown something happens in other?

Correct me if I wrong

Then check that NAME of all of your original `select` is unique  (till version 3.0.0 I have used ID attribute for creating internal referencing, but from version 3.0.0 start using NAME  since I have decieded that ID is "less obligated", - so I trust more NAME presence and uniquess). Or you do not use NAME at all and want to stay with ID?

In any case there is possibility to configure ID generation:


             $('#bsMultiSelectJson1').bsMultiSelect(
                        {
                                  createInputId: function(c){
                                                  return `${c.containerClass}-bsMultiSelectJson1-filterInput-id`;
                                              }

                                  createCheckBoxId : function(c,option){
                                                  return `${c.containerClass}-bsMultiSelectJson1-generated-checkbox-${option.id}-id`;
                                              }
                             },

                             }
                );

But us I understant it right now is not very usefull, since bsMultiSelectJson1 is constant when you possbly will need to initialize many components at once `$('select[multiselect]')` .

**Comment by asbag** [comment]
Hi!!!
thank you for your help!!! it worked. I was using the last version, because as it didn't work I downloaded the last one. However it didn't work. After your answer, I noticed that I didn't have any name in the selects but unique IDs, I also add unique NAMES and it worked. Thank you!!
