### ISSUE TITLE
Columns

### ISSUE THREAD

**Issue by marcelo-maciel** [DashboardCode/BsMultiSelect#21]
Hi!
Great work, congratulations!

I have a long list of options, like 60 or more, then i thinked about split the result in columns, to avoid long scroll.
Is there this option? If not, I think that is a good idea.

Thanks!

**Comment by rpokrovskij** [comment]
This is a good idea and that is because the pulldown list is left "compact" (not stretched from side to side). 

You can add id manipulating css:  

1)  in scss

```
 ul.dropdown-menu {
        list-style-type: none;
        column-count:2 ..
```

2) in configuration using css through js configuration parameters 

```
$multiSelects.bsMultiSelect(
    cssPatch : { 
        choices: {columnCount:'2' },
    }
);
```

There are drawbacks of this - you wille need to manage it on mobile platforms 'manually'. Share your expirience. If it will be reach enough we would add the plugin that manage columns from js (I guess that SCSS can manage them from @media ). 

Currently I'm working on plugins API.

**Comment by rpokrovskij** [comment]
https://dashboardcode.github.io/BsMultiSelect/snippetColumns.html
