### ISSUE TITLE
How to clear selected options

### ISSUE THREAD

**Issue by alqa-dash** [DashboardCode/BsMultiSelect#8]
Hello,

Is it possible to clear all selected options at once by clicking some button?
And one more thing: is it possible to draw dropdown arrow somewhere in select element to let users know that there is some kind of list of items to choose?

**Comment by alqa-dash** [comment]
Just switched to another multiselect control

**Comment by rpokrovskij** [comment]
1) for quick delete press backspace in input several times.
2) no , it is an input style "select". it has methaphor of input with autosuggestion. when you click on it or o with TAB on in - it opens the dialog, and user understand what to do next. 
but since it is a bootstrap you can use BS inputgroup with prepend, append staic elements.

**Comment by rajat10times** [comment]
Hi,

Is there any method to reset/clear all selected options ?

**Comment by rpokrovskij** [comment]
If we talk about selection status only: $('#myMultiSelectId').bsMultiSelect('DeselectAll') or  bsMultiSelect.deselectAll

This was in demo.
